package ventanas;

import clases.Conexion;
import java.sql.*;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class GestordeDatos extends javax.swing.JFrame {

    String user, nombre_usuario;
    int sesion_usuario;

    public GestordeDatos() {
        initComponents();
        user = Login.user;
        sesion_usuario = Administrador.sesion_usuario;
        setTitle("Gestor de datos - Sesión de " + user);
        setLocationRelativeTo(null);
        setSize(550,330);
        setResizable(false);
        
        if (sesion_usuario == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE); 
        }
        
        ImageIcon fondoPantalla = new ImageIcon("src/main/java/images/wallpaper.jpg");
        Icon icono = new ImageIcon(fondoPantalla.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        Toolkit miPantalla = Toolkit.getDefaultToolkit();
        Image miIcono = miPantalla.getImage("src/main/java/images/icono.png");
        setIconImage(miIcono);
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_usuario from usuarios where username =?");
            pst.setString(1, user);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
              nombre_usuario = rs.getString("nombre_usuario");
              jLabel_nombreusuario.setText("Bienvenido " + nombre_usuario);
            
            }
            
        } catch (SQLException e) {
            System.err.println("Error en consultar Gestor de Datos");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_nombreusuario = new javax.swing.JLabel();
        jButton_registrarCliente = new javax.swing.JButton();
        jButton_gestionarClientes = new javax.swing.JButton();
        jButton_imprimir = new javax.swing.JButton();
        jLabel_registrar = new javax.swing.JLabel();
        jLabel_gestionar = new javax.swing.JLabel();
        jLabel_imprimir = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nombreusuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_nombreusuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreusuario.setText("jLabel1");
        getContentPane().add(jLabel_nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton_registrarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manuel\\Documents\\NetBeansProjects\\DataSystem\\src\\main\\java\\images\\add.png")); // NOI18N
        jButton_registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_registrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 100));

        jButton_gestionarClientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manuel\\Documents\\NetBeansProjects\\DataSystem\\src\\main\\java\\images\\informationuser.png")); // NOI18N
        jButton_gestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gestionarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_gestionarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, 100));

        jButton_imprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manuel\\Documents\\NetBeansProjects\\DataSystem\\src\\main\\java\\images\\impresora.png")); // NOI18N
        jButton_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imprimirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 120, 100));

        jLabel_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_registrar.setText("Registrar cliente");
        getContentPane().add(jLabel_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel_gestionar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_gestionar.setText("Gestionar clientes");
        getContentPane().add(jLabel_gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 180, -1, -1));

        jLabel_imprimir.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_imprimir.setText("Imprimir clientes ");
        getContentPane().add(jLabel_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Desarrollado por Manuel Sánchez ®");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 20));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarClienteActionPerformed
        new RegistrarClientes().setVisible(true);
    }//GEN-LAST:event_jButton_registrarClienteActionPerformed

    private void jButton_gestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gestionarClientesActionPerformed
        new GestionarClientes().setVisible(true);
    }//GEN-LAST:event_jButton_gestionarClientesActionPerformed

    private void jButton_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imprimirActionPerformed

    Document documento = new Document();
    
        try {
            // elige la ruta dondde se guardará el archivo, en este caso en el escritorio
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/ListaClientes.pdf"));
            
            // header
            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src\\main\\java\\images\\BannerPDF.jpg");
            header.scaleToFit(650, 1000);
            header.setAlignment(Chunk.ALIGN_CENTER);
            
            // parrafo
            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.add("Lista de clientes. \n \n");
            parrafo.setFont(FontFactory.getFont("Tahoma", 18, Font.BOLD, BaseColor.DARK_GRAY ));
            
            documento.open();
            documento.add(header);
            documento.add(parrafo);
            
            PdfPTable tabla = new PdfPTable(5);
            tabla.addCell("ID del cliente");
            tabla.addCell("Nombre");
            tabla.addCell("E-mail");
            tabla.addCell("Teléfono");
            tabla.addCell("Dirección");
            
            try {
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from clientes");
            ResultSet rs = pst.executeQuery();
            
                if (rs.next()) {
                    do{
                    
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                        
                    } while(rs.next());
                        documento.add(tabla);
                }
            } catch (SQLException e) {
                System.err.println("Error al generar la lista de clientes " + e);
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "Lista de clientes creada correctamente.");
            
            } catch (Exception e) {
                System.err.println("Error al generar PDF");
        }

    }//GEN-LAST:event_jButton_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestordeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestordeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestordeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestordeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestordeDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_gestionarClientes;
    private javax.swing.JButton jButton_imprimir;
    private javax.swing.JButton jButton_registrarCliente;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_gestionar;
    private javax.swing.JLabel jLabel_imprimir;
    private javax.swing.JLabel jLabel_nombreusuario;
    private javax.swing.JLabel jLabel_registrar;
    // End of variables declaration//GEN-END:variables
}
