package ventanas;

import clases.Conexion;
import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class Tecnico extends javax.swing.JFrame {

    String user, nombre_usuario;
    int sesion_usuario;

    public Tecnico() {
        initComponents();
        user = Login.user;
        sesion_usuario = Administrador.sesion_usuario;
        setTitle("Técnico - Sesión de " + user);
        setLocationRelativeTo(null);
        setSize(550,330);
        setResizable(false);
        
        if (sesion_usuario == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE); 
        }
        
        ImageIcon fondoPantalla = new ImageIcon("src/main/java/images/wallpaper.jpg");
        Icon icono = new ImageIcon(fondoPantalla.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        Toolkit miPantalla = Toolkit.getDefaultToolkit();
        Image miIcono = miPantalla.getImage("src/main/java/images/icono.png");
        setIconImage(miIcono);
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_usuario from usuarios where username =?");
            pst.setString(1, user);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
              nombre_usuario = rs.getString("nombre_usuario");
              jLabel_nombreusuario.setText("Bienvenido " + nombre_usuario);
            
            }
            
        } catch (SQLException e) {
            System.err.println("Error en consultar nombre de Técnico");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_nombreusuario = new javax.swing.JLabel();
        jButton_gestionEquipo = new javax.swing.JButton();
        jButton_graficaEstatus = new javax.swing.JButton();
        jButton_graficaMarcas = new javax.swing.JButton();
        jLabel_registrar = new javax.swing.JLabel();
        jLabel_gestionar = new javax.swing.JLabel();
        jLabel_imprimir = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nombreusuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_nombreusuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreusuario.setText("jLabel1");
        getContentPane().add(jLabel_nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton_gestionEquipo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manuel\\Documents\\NetBeansProjects\\DataSystem\\src\\main\\java\\images\\apoyo-tecnico.png")); // NOI18N
        jButton_gestionEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gestionEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_gestionEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 100));

        jButton_graficaEstatus.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manuel\\Documents\\NetBeansProjects\\DataSystem\\src\\main\\java\\images\\grafica.png")); // NOI18N
        jButton_graficaEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_graficaEstatusActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_graficaEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, 100));

        jButton_graficaMarcas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manuel\\Documents\\NetBeansProjects\\DataSystem\\src\\main\\java\\images\\grafica.png")); // NOI18N
        jButton_graficaMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_graficaMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_graficaMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 120, 100));

        jLabel_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_registrar.setText("Gestión de equipo");
        getContentPane().add(jLabel_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 180, -1, -1));

        jLabel_gestionar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_gestionar.setText("Gráfica de estatus");
        getContentPane().add(jLabel_gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 180, -1, -1));

        jLabel_imprimir.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_imprimir.setText("Gráfica de marcas");
        getContentPane().add(jLabel_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 180, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Desarrollado por Manuel Sánchez ®");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 20));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_gestionEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gestionEquipoActionPerformed
        new GestionarEquipos().setVisible(true);
        
    }//GEN-LAST:event_jButton_gestionEquipoActionPerformed

    private void jButton_graficaEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_graficaEstatusActionPerformed
        new GraficaEstatus().setVisible(true);
        
    }//GEN-LAST:event_jButton_graficaEstatusActionPerformed

    private void jButton_graficaMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_graficaMarcasActionPerformed
        new GraficaDeMarcas().setVisible(true);
    
    }//GEN-LAST:event_jButton_graficaMarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_gestionEquipo;
    private javax.swing.JButton jButton_graficaEstatus;
    private javax.swing.JButton jButton_graficaMarcas;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_gestionar;
    private javax.swing.JLabel jLabel_imprimir;
    private javax.swing.JLabel jLabel_nombreusuario;
    private javax.swing.JLabel jLabel_registrar;
    // End of variables declaration//GEN-END:variables
}
